name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, is it me you're looking for?"
      - name: Print home directory details
        run: echo "${HOME}"
      - name: Print goodbye
        run: echo "Bye bye"
      
